### ISSUE TITLE
Backslash in `.( )` disappears

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#66] opened 2024-11-10 14:47 UTC
The phrase:
```forth
.( \ foobar)
```
shall print "`\ foobar`", but it prints "` foobar`".

**Comment by SirWumpus** [comment] 2024-11-10 15:11
By design

https://github.com/SirWumpus/post4/blob/master/doc/standard.md#-ccc-2

**Comment by ruv** [comment] 2024-11-10 15:34
Any rationale?    Why not introduce `.\(` similar to `s\"` ?

**Comment by SirWumpus** [comment] 2024-11-10 15:52
Well I'd have to think back 2 or 3 years to the actually reason, but I suspect I found it annoying and inconsistent that any word that had a terminating delimiter did not support backslash escape by default instead the standard doubled up on some words, but not others:  `S"` and `S\\"`, `C"` but no `C\"`, `(` but no `\(`, `."` but no `.\"` and I'm sure others.  My plan was to supported escaping as an extension cause I find it more useful than creating extra escaping words.

**Comment by ruv** [comment] 2024-11-10 16:16
The problem is backward compatibility, and compatibility between Forth systems. Portable programs and old programs do not expect that "`\`" has a special meaning in the string literals of `s"`, `c"`, `."`, `.(`.   So, we have to introduce new words that support escaping. 

Usually, `s\"` is enough.  In very rare cases when we need `.( "(foobar)")`, it can be written as `s\" \"(foobar)\"" type`.

In general, I prefer unique delimiters over escaping. For example, see the proposed [word `S$`](http://forth.sourceforge.net/word/s-dollar/index.html).

Also, I want to implement something like [Dollar-Quoted String Constants](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) from PostgreSQL.

**Comment by SirWumpus** [comment] 2024-11-10 16:35
> The problem is backward compatibility, and compatibility between Forth systems. Portable programs and old programs do not expect that "`\`" has a special meaning in the string literals of `s"`, `c"`, `."`, `.(`. So, we have to introduce new words that support escaping.
> 
> Usually, `s\"` is enough. In very rare cases when we need `.( "(foobar)")`, it can be written as `s\" \"(foobar)\"" type`.

Well doesn't work for me since like `( ccc)` that can span multiple lines, `.( ccc)` can span multiple lines.  I've used to display screenful of instructions.

> In general, I prefer unique delimiters over escaping. For example, see the proposed [word `S$`](https://web.archive.org/web/20171226233203/http://forth.sourceforge.net/word/s-dollar/index.html) (the link changed to an archived copy).

Don't like this solution because you still have a the problem of needing to display the delimiter; what if all the other delimiter choices are part of the text, like for online instructions, you might still need to escape the closing delimiter.  Also devs from other languages will be familiar with backslash escape, they appear in all the C syntax like languages.

I'll have to think about how much I want backwards compatibility.  When I first wrote some of these words, I didn't think I'd have anyone interested in my implementation, especially some Forth guru.

**Comment by ruv** [comment] 2024-11-10 17:07
> doesn't work for me since like ( ccc) that can span multiple lines, .( ccc) can span multiple lines. I've used to display screenful of instructions.

The standard does not prevent a Forth system from providing `s"` and `s\"` that support multi-line string literals.  A standard program simply cannot rely that these words supporting multi-line literals. A system-specific program/extension may use them.


> Don't like this solution because you still have a the problem of needing to display the delimiter;

[Dollar-Quoted String](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) does not have this problem because you choose multi-character delimiter:
```text
$some-delimiter$ any text ( ) ' ' \ " " $some-delimiter$
```
Of course, it can be multi-line.


> I'll have to think about how much I want backwards compatibility.

It is not only backwards compatibility, but also compatibility between different Forth systems. E.g., I expect that my my program outputs the same text (in the essential parts) on different Forth systems.

**Closed** 2024-11-10 21:34 UTC
